name: scl
channels:
  - defaults
dependencies:
  - python=3.10.9
  - perl
  - pip
  - pip:
    - jupyter
    - matplotlib
    - networkx
    - numpy
    - pandas
    - ray
    - scikit-learn
    - scipy
    - termcolor
    - igraph
